### ISSUE TITLE
语法错误

### ISSUE THREAD

**Issue by skysunsun** [Vespa314/chan.py#13]
`Traceback (most recent call last):

  File "D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-13c9d472da86>", line 1, in <module>
    from Chan import CChan

  File "D:\chan.py\Chan.py", line 12, in <module>
    from KLine.KLine_List import CKLine_List

  File "D:\chan.py\KLine\KLine_List.py", line 5, in <module>
    from BuySellPoint.BSPointList import CBSPointList

  File "D:\chan.py\BuySellPoint\BSPointList.py", line 8, in <module>
    from Seg.SegListComm import CSegListComm

  File "D:\chan.py\Seg\SegListComm.py", line 92
    if peak_bi := FindPeakBi(bi_lst[last_seg_end_bi.idx+3:], is_high=True):
                ^
SyntaxError: invalid syntax`
^_^语法错误是我没想到的，哈哈哈哈

**Comment by Vespa314** [comment]
readme有写，基于至少python3.11才可以运行成功。海象运算符是3.8之后引入的。
