### ISSUE TITLE
CBi.Cal_Rsi 运行错误

### ISSUE THREAD

**Issue by Mjzs12138** [Vespa314/chan.py#47]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/masonchen/Repos/chan.py/Common/cache.py", line 32, in __call__
    result = self.func(*args, **kwargs)
  File "/Users/masonchen/Repos/chan.py/Bi/Bi.py", line 212, in Cal_Rsi
    rsi_lst.extend(klu.rsi for klu in klc.lst)
  File "/Users/masonchen/Repos/chan.py/Bi/Bi.py", line 212, in <genexpr>
    rsi_lst.extend(klu.rsi for klu in klc.lst)
AttributeError: 'CKLine_Unit' object has no attribute 'rsi'

**Comment by Vespa314** [comment]
CChanConfig里面是不是没有打开cal_rsi开关？

**Comment by Mjzs12138** [comment]
谢谢，的确是这样
