### ISSUE TITLE
将strategydemo中改为1分钟级别，即“lv_list = [KL_TYPE.K_1M]”，就会报错，而5分钟及以上级别不会报错

### ISSUE THREAD

**Issue by cdlknfdag** [Vespa314/chan.py#54]
login success!
logout success!
Traceback (most recent call last):
  File "D:\stock-chan\chan.py-main\Debug\strategy_demo.py", line 34, in <module>
    for chan_snapshot in chan.step_load():  # 每增加一根K线，返回当前静态精算结果
  File "D:\stock-chan\chan.py-main\Chan.py", line 122, in step_load
    for idx, snapshot in enumerate(self.load(self.conf.trigger_step)):
  File "D:\stock-chan\chan.py-main\Chan.py", line 198, in load
    yield from self.load_iterator(lv_idx=0, parent_klu=None, step=step)  # 计算入口
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stock-chan\chan.py-main\Chan.py", line 242, in load_iterator
    kline_unit = self.get_next_lv_klu(lv_idx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stock-chan\chan.py-main\Chan.py", line 110, in get_next_lv_klu
    return self.g_kl_iter[lv_idx][0].__next__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stock-chan\chan.py-main\Chan.py", line 89, in load_stock_data
    for KLU_IDX, klu in enumerate(stockapi_instance.get_kl_data()):
  File "D:\stock-chan\chan.py-main\DataAPI\BaoStockAPI.py", line 81, in get_kl_data
    raise Exception(rs.error_msg)
Exception: 请求数据类型不正确
![190a601b1c65e2762e06c8ca7f02a1c](https://github.com/Vespa314/chan.py/assets/175038979/b58290dd-21f8-462e-84ae-d0795550876f)
![357c32d73de65910afa84d986170946](https://github.com/Vespa314/chan.py/assets/175038979/7439f8f3-7d21-412b-9f99-3b247b574418)

**Comment by Vespa314** [comment]
那应该就是演示的数据源类baostock不支持获取1分钟的
